### ISSUE TITLE
npm run build-minified error

### ISSUE THREAD

**Issue by warshooter** [sqren/fb-sleep-stats#10]
Getting the following error when using **npm run build-minified**:

ERROR in ./src/browser/components/main.jsx
Module parse failed: /Applications/MAMP/htdocs/node_modules/fb-sleep-stats/src/browser/components/main.jsx Line 34: Unexpected token <
You may need an appropriate loader to handle this file type.
|     render() {
|         var isAuthenticated = this.state.isAuthenticated;
|         var loginButton = <div className="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false"></div>
|         return (
|             <div>
 @ ./src/browser/main.js 1:0-32

any idea?

**Comment by fuel45** [comment]
Im stuck at the same stage, getting this error..

Output filename not configured.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-minified"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! fb-sleep-stats@0.5.0 build-minified: `webpack --progress --optimize-minimize`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the fb-sleep-stats@0.5.0 build-minified script 'webpack --progress --optimize-minimize'.
npm ERR! This is most likely a problem with the fb-sleep-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --optimize-minimize
npm ERR! You can get their info via:
npm ERR!     npm owner ls fb-sleep-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Theden/npm-debug.log
MacBook-Pro:~ Theden$

**Comment by napieraj** [comment]
same as above

**Comment by sorenlouv** [comment]
What version are you running. This has been developed on Node 4. I'm pretty sure it also works on 0.12. Haven't tried Node 5

**Comment by fuel45** [comment]
MacBook-Pro:~ Theden$ node -v
v4.3.1
MacBook-Pro:~ Theden$

**Comment by warshooter** [comment]
v5.6.0

**Comment by napieraj** [comment]
```
MacBook-Pro:fb-sleep-stats oskar$ node -v
v4.0.0
```

**Comment by napieraj** [comment]
> $ cat npm-debug.log 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build-minified' ]
> 2 info using npm@2.14.2
> 3 info using node@v4.0.0
> 4 verbose run-script [ 'prebuild-minified', 'build-minified', 'postbuild-minified' ]
> 5 info prebuild-minified fb-sleep-stats@0.5.0
> 6 info build-minified fb-sleep-stats@0.5.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info fb-sleep-stats@0.5.0 Failed to exec build-minified script
> 9 verbose stack Error: fb-sleep-stats@0.5.0 build-minified: `webpack --progress --optimize-minimize`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:817:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid fb-sleep-stats@0.5.0
> 11 verbose cwd /Users/oskar/fb-sleep-stats
> 12 error Darwin 15.0.0
> 13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-minified"
> 14 error node v4.0.0
> 15 error npm  v2.14.2
> 16 error code ELIFECYCLE
> 17 error fb-sleep-stats@0.5.0 build-minified: `webpack --progress --optimize-minimize`
> 17 error Exit status 1
> 18 error Failed at the fb-sleep-stats@0.5.0 build-minified script 'webpack --progress --optimize-minimize'.
> 18 error This is most likely a problem with the fb-sleep-stats package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     webpack --progress --optimize-minimize
> 18 error You can get their info via:
> 18 error     npm owner ls fb-sleep-stats
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by napieraj** [comment]
a trailing tab had made its way into my configuration, all fixed now

**Comment by fuel45** [comment]
How did you manage to fix it exactly ?

**Comment by sorenlouv** [comment]
Did you have any errors when running `npm install` ?
You can try deleting your node modules and installing them again

```
rm -rf node_modules
npm install
npm run build-minified
```

**Comment by warshooter** [comment]
removed everything including node and re-installed. Now it works. Likely it was a security problem with my company's network.
