### ISSUE TITLE
"Given URL is not allowed by the Application configuration" on non-localhost server

### ISSUE THREAD

**Issue by daveystruijk** [sqren/fb-sleep-stats#11]
The server works fine on my local machine with my own AppId, but when I tried running it on a cloud instance, Facebook's OAuth window gave me this error: `Given URL is not allowed by the Application configuration`. Has anyone gotten it to work on a remote ip / domain?

Because my server only has an IP address, I also tried setting one in my /etc/hosts file and configuring my facebook app to use that domain, but I still get the same error.

**Comment by sorenlouv** [comment]
If you want to run this on anything besides `localhost:3000` you will need to create you own Facebook app id. See steps here:
https://gist.github.com/sqren/1ac0f5d316fcbd46d8c1

**Comment by daveystruijk** [comment]
Yep, I'm already using my own AppId, configured to `mydomain:9000` (also tried changing everything to port 80), but it still gives me this error. I'll look into it a little more, maybe I've misconfigured something.

**Comment by sorenlouv** [comment]
I misspoke before. Try port 3000.

**Comment by sorenlouv** [comment]
localhost:3000

**Comment by daveystruijk** [comment]
Fixed it! Seems like the Facebook API version was outdated. I have no idea why that would make a difference between local/remote, but the following PR should fix it: #13
