### ISSUE TITLE
npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.

### ISSUE THREAD

**Issue by vatthikorn** [sqren/fb-sleep-stats#12]
I ran
`npm install`
and got this error

**Comment by sorenlouv** [comment]
It's a warning from one of the dependencies. Shouldn't be anything critical. Do you see any errors?

**Comment by sorenlouv** [comment]
Please re-open an issue with additional details if your continue experiencing problems.
