### ISSUE TITLE
npm run scrape giving error "0 active users"

### ISSUE THREAD

**Issue by ghost** [sqren/fb-sleep-stats#16]
PS C:\Windows\system32> cd C:\dev\fb-sleep-stats-master
PS C:\dev\fb-sleep-stats-master> npm run scrape

> fb-sleep-stats@0.5.0 scrape C:\dev\fb-sleep-stats-master
> node ./scrape.js
> 2/23/2016, 6:24:28 PM  -  0 active users

There definitely are active users on my fb right now so not sure why that message shows.

**Comment by niraj4** [comment]
From what I read the scraper uses the "last activity" time stamp. Let the scraper run for an hour or so and see if you get different results in the server that maps it graph in your browser

**Comment by ghost** [comment]
I also thought that was the issue but after leaving it on during the night it still says 0 active users every time it does the query.

(I got it working in Ubuntu 15.10 virtualbox with no problems but can't get it to find users when running it in Windows 8.1.)

**Comment by sorenlouv** [comment]
@dwv That sounds strange. What the crawler essentially does is:
1) www.messenger.com 
2) "view source"
3) Find "lastActiveTimes" object

Try to do the above manually, and let me know if you find the "lastActiveTimes" object, and whether it's empty or contain data.

**Comment by ghost** [comment]
@sqren I did try that and it is not empty. Also double checked the cookie and the fb id.

**Comment by sorenlouv** [comment]
I did some changes to how users are retrieved. Try the following:

```
git pull
rm -rf node_modules
npm install
npm run webpack
```

Hopefully that'll fix it.

**Comment by ghost** [comment]
This did indeed fix the issue I had in windows.

**Comment by sorenlouv** [comment]
Glad to hear.
