### ISSUE TITLE
Only runs for a short period of time showing a few friends

### ISSUE THREAD

**Issue by tim-sanchez** [sqren/fb-sleep-stats#17]
Everything seems to work properly with no errors, but when running the app it stops showing results after about 15-20 minutes. It also only shows a select few of my friends. In addition, nothing appears under period or duration.

I have been running it for around 3 hours now, and still the only entries are from the first 15 minutes or so.

**Comment by Skokez** [comment]
happens the same here

**Comment by niraj4** [comment]
Are you leaving the scraper on? Every 10 minutes it will show a line  "<time stamp> - x active users"

You can also check `fb-sleep-stats/src/server/services/db.json` to make sure that the file is getting updated every 10 minutes

**Comment by sorenlouv** [comment]
You have to run the following, and not stop it.

```
npm run scrape
```

Every 10 minute it will poll Facebook. It will only fetch the users who were online within the past 10 minutes, which is why it won't show all of your friends until they have all been online.

**Comment by Skokez** [comment]
aight im leaving it running ill feedback in 10min ;)

**Comment by shemul** [comment]
yeah , running the scrape parallay , it started showing some result ..

**Comment by Skokez** [comment]
yea but still no results under period/duration

**Comment by shemul** [comment]
@shokez ^ same here

**Comment by sorenlouv** [comment]
The results are saved in `src/server/services/db.json`. Can you paste the output of that file?

**Comment by Skokez** [comment]
```
{
  "updates": [
    <redacted>
  ],
  "users": {
    <redacted>
  }
}

```

**Comment by Skokez** [comment]
btw the 10 min thing is working 
it uploads the results

**Comment by sorenlouv** [comment]
@Skokez Okay, and the results you posted look fine (I removed the user_ids btw)

**Comment by Skokez** [comment]
so... why isn't showing any data? 
thanks btw

**Comment by sorenlouv** [comment]
Do you have an ad-blocker running?
Did you click "Login with Facebook"?

**Comment by Skokez** [comment]
Stop'd ad-blocker still nothing 
and yes I clicked on "Login with facebook"

**Comment by Skokez** [comment]
and I still get the same amount of friends on the list

**Comment by sorenlouv** [comment]
> and I still get the same amount of friends on the list
> So you see a list of friends on the left? But when you click any of them, no results show up?

Do you see any errors in the console?

**Comment by sorenlouv** [comment]
If you open this url [http://localhost:3000/rest/users](http://localhost:3000/rest/users) do you see something like below?

```
[
    {
        name: "<friend name>",
        id: "<friend id>",
        count: 2
    }
    ...
]
```

**Comment by Skokez** [comment]
I dont see any errors
and i cant access the link

**Comment by sorenlouv** [comment]
Sorry, I meant to write [http://localhost:3000/rest/users](http://localhost:3000/rest/users)

**Comment by ghost** [comment]
same for me. It will show `This webpage is not available. ERR_CONNECTION_REFUSED` in the browser.

Edit: Nevermind. It started showing up.

**Comment by sorenlouv** [comment]
Ahh, re-reading the original question and see this:

>  nothing appears under period or duration

It will not show anything under "period - duration" until it has enough data points. It should run for at _least_ 24 hours until anything will show up.

I'll make an update to the UI, to make it more clear.

**Comment by Skokez** [comment]
ho ok great so evertything working fine thanks
