### ISSUE TITLE
App not set up

### ISSUE THREAD

**Issue by vidia** [sqren/fb-sleep-stats#2]
I am getting he following error: 

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by whizzzkid** [comment]
Can confirm this. I guess you can edit the appId from src/browser/services/facebook.js to your own appid to make it work.

**Comment by whizzzkid** [comment]
Yep create your own app and create entry for localhost in the settings (http://stackoverflow.com/questions/21295872/facebook-app-localhost-no-longer-works-as-app-domain) and set the app id in src/browser/services/facebook.js

It works now.

**Comment by SevenBlocks** [comment]
@whizzzkid  Did you change anything other than the app id in facebook.js? I created a facebook app, added localhost to domains and set the url to http://localhost:3000/, but I'm still getting the "App Not Setup" message in the browser.

**Comment by chhabs** [comment]
in this order:
1. delete your fb app
2. in  shell: sudo npm uninstall 
3. recreate a fb app and add http://localhost:3000 in URL but not in domain name
4. change src/browser/services/facebook.js with your app ID and save  
5. in  shell: npm install
6. in  shell: npm run build-minified
7. in  shell: npm start
8. in new shell window :npm run scrape
9. using firefox : http://localhost:3000
10. if you can't see data in firefox, in new shell window: npm run watch

make sure .node and npm are updated

**Comment by SevenBlocks** [comment]
@chhabs Your steps worked. Awesome! Minor typos: a couple places you've got the typo "nmp" instead of "npm".

**Comment by juanda2** [comment]
worked here as well, huge thanks!

**Comment by sorenlouv** [comment]
Fixed by https://github.com/sqren/fb-sleep-stats/pull/6
