### ISSUE TITLE
Can i change it so it scrapes every minute? 

### ISSUE THREAD

**Issue by RogerFederer17** [sqren/fb-sleep-stats#22]
And if i can, what difference would actually make? Why 10 minutes the default?

**Comment by sorenlouv** [comment]
Good point. I'll make it configurable when I have time.
I made it 10 minutes, because it seemed to be often enough to get an accurate picture, and didn't want Facebook to start blocking me.

**Comment by ghost** [comment]
@RogerFederer17 Can't you change that in scraper.js ?

**Comment by sorenlouv** [comment]
You can change it here
https://github.com/sqren/fb-sleep-stats/blob/master/scrape.js#L6

**Comment by ghost** [comment]
@sqren Maybe a bit weird question, but is there any way I can acces the data that is scraped? like put it into a JSON file?

**Comment by sorenlouv** [comment]
The data is stored here: `fb-sleep-stats/src/server/services/db.json`

**Comment by ghost** [comment]
@sqren Thanks! Could you maybe explain how this is build up? I don't see any time, just updates and users.

**Comment by krijoh92** [comment]
Why not just change the `pollingInterval` in `config/development.json` ? :) 

It's default set to `600`, assuming this value is seconds, that would mean 10 minutes. So I'm guessing changing this to `60`, it would mean 1 minute ?

Right, @sqren ?

**Comment by sorenlouv** [comment]
@krijoh92 Yes. I added that feature two hours ago :)

**Comment by krijoh92** [comment]
Hah, well good timing by me then, I clone this repo 42 minutes ago :) Thanks for the good work Søren :)
