### ISSUE TITLE
Error Cloning: Permission denied (publicly)

### ISSUE THREAD

**Issue by vibhorj** [sqren/fb-sleep-stats#25]
Thanks for this project!
I used the commend: git clone git@github.com:sqren/fb-sleep-stats.git
and get this error (Mac OSX Terminal app)

**Cloning into 'fb-sleep-stats'...
Permission denied (publicly).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
**

**Comment by chhabs** [comment]
Use the https:// url in the github page instead.

**Comment by vibhorj** [comment]
ok thx. yeah it worked !
thanks for rapid response :=)
