### ISSUE TITLE
Scrape failing? Could not get users: Promise is not defined undefined

### ISSUE THREAD

**Issue by borndangerous** [sqren/fb-sleep-stats#29]
Hey, haven't been able to debug this properly. On running `npm run scrape`, it clearly gets as far as pulling the active users (and `users` object has their IDs)... but then I see this Promises-related error:

**`Could not get users: Promise is not defined undefined`**

Here's it is with a few lines for context...

```
> node ./scrape.js

Tue Feb 23 2016 07:45:17 GMT-0500 (EST)  -  1 active users
A error occured while scraping. Please check to make sure your development.json config is correct
Tue Feb 23 2016 07:45:17 GMT-0500 (EST)  - Could not get users: Promise is not defined undefined
```

Not sure if it's working or failing before the pulled data gets persisted anywhere.

The stats/dashboard sidebar doesn't present any user records.

Thoughts?

**Comment by sorenlouv** [comment]
I haven't seen this error before.
What version of node do you have? It could help to update to the latest stable version of whatever major version you are on (v5.7.0, v4.3.1 or v0.12.10)

When you've updated rebuild your node_modules:

```
rm -rf node_modules
npm install
npm run build-minified
```

**Comment by sorenlouv** [comment]
If updating Node doesn't work, try adding this to the beginning of the [webpack config](https://github.com/sqren/fb-sleep-stats/blob/master/webpack.config.js):

```
require('es6-promise').polyfill() 
```

http://stackoverflow.com/a/32940141/434980

**Comment by borndangerous** [comment]
Much appreciate the quick reply man. Actually I kicked off a node update and module rebuild right after posting this. Just tried again and all works beautifully. Thinking it was specifically due to an old node version, in case anyone else runs into the same.

Love that you've shared the code for this. Toying with things now. :)

David
