### ISSUE TITLE
Only shows a white screen when you run npm start in local host

### ISSUE THREAD

**Issue by TheOriginalPedro** [sqren/fb-sleep-stats#31]
<img width="1280" alt="screen shot 2016-02-23 at 16 23 54" src="https://cloud.githubusercontent.com/assets/17431335/13258142/dc066458-da49-11e5-9ce5-1a119d5e135d.png">

**Comment by jgkamat** [comment]
You have to log in before it will show you anything (not the best UI choice).

**Comment by TheOriginalPedro** [comment]
Awesome, thank you!
