### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by canvural** [sqren/fb-sleep-stats#35]
After pulling the recent changes i'm getting this error when try to access to server

`Could not get list [TypeError: _(...).map(...).orderBy is not a function]`

No stack trace or anything, so i don't where the error is.

**Comment by sorenlouv** [comment]
You'll have to rebuild your dependencies:

```
rm -rf node_modules
npm install
npm run webpack
```

**Comment by canvural** [comment]
Ooh, ok. That did the trick.
