### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by njbbaer** [sqren/fb-sleep-stats#36]
Error occurred on AWS EC2 server running Ubuntu 14.04. Works fine on my local Windows machine with the same development.json file.

> node ./scrape.js
> 
> Polling every 600 seconds
> Sat Feb 27 2016 17:55:21 GMT+0000 (UTC)  - Active users:  44 / 259
> Sat Feb 27 2016 17:55:21 GMT+0000 (UTC) An error occured while scraping. Please check to make sure your development.json config is correct [ReferenceError: Promise is not defined]

**Comment by sorenlouv** [comment]
You need to update Node.
It should help to update to the latest stable version of whatever major version you are on (v5.7.0, v4.3.1 or v0.12.10)

See https://github.com/sqren/fb-sleep-stats/issues/29

When you've updated rebuild your dependencies:

```
rm -rf node_modules
npm install
npm run webpack
```

**Comment by njbbaer** [comment]
Thanks, that did the trick.
