### ISSUE TITLE
ERROR in Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by colaflaske** [sqren/fb-sleep-stats#37]
Any idea how to fix this? It seems like lodash has the isFunction function in lodash/\* and not lodash/lang/\* as of 4.0.

> PS C:\Users\Colaflaske\fb-sleep-stats> npm install
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
> npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
> PS C:\Users\Colaflaske\fb-sleep-stats> npm run webpack
> 
> > fb-sleep-stats@0.9.0 webpack C:\Users\Colaflaske\fb-sleep-stats
> > webpack --progress
> 
> Hash: e2a1fab2f1d993dfabc2
> Version: webpack 1.12.14
> Time: 36ms
>     + 1 hidden modules
> 
> ERROR in Cannot find module 'lodash/lang/isFunction'

**Comment by sorenlouv** [comment]
Have you tried re-installing the node modules?

```
rm -rf node_modules
npm install
npm run webpack
```

**Comment by colaflaske** [comment]
And of course something that simple works. I'm a doofus sometimes..
