### ISSUE TITLE
blank page, even after clicking login to app on localhost webpage

### ISSUE THREAD

**Issue by magicus1** [sqren/fb-sleep-stats#38]
![fb sleep](https://cloud.githubusercontent.com/assets/17537183/13384641/ddba83e0-de97-11e5-8dde-f2a612abef0f.png)

Hey I followed the guide and everything is working, except that the information is not being displayed. The output file db.json has been created and i clicked the facebook login icon login, but nothing happens after that.

**Comment by canvural** [comment]
Did you give permission to the app?

**Comment by magicus1** [comment]
Im not sure. i followed the README guide. How can I give permissions to the app?

**Comment by sorenlouv** [comment]
Do you see any error in the browser Development Tools Console?

**Comment by sorenlouv** [comment]
Do you have an adblocker/ghostery/disconnect (something that disables Facebook login).

**Comment by magicus1** [comment]
I dont see any errors in the Development Tools Console, but im not sure what im looking for. 

I dont have an adblocker and I tried to access localhost on both Chrome and IE. 
Maybe there is another way to display the data? I mean I have the output file so maybe I can use a program to open it other than the webbrowser?

**Comment by magicus1** [comment]
it didnt work with chrome or ie.. but with microsoft edge i got it to work!.. maybe its something to do with the no referrals or block third party cookies i set in the settings earlier on those browsers....

**Comment by xsoft** [comment]
I have some issue. Console output were:

`unreachable code after return statement bundle.js:31517:5`
`"Download the React DevTools for a better development experience: https://fb.me/react-devtools" bundle.js:244:10
`
`unreachable code after return statement bundle.js:31517:5`

```
Facebook App Id: ************** bundle.js:59942:10
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
```

(I guess that Id: *************\* will be an issue. I have there my own FB app id).

**Comment by xsoft** [comment]
Just dont eg. "port forward" (like localhost:3000). It need to have URL noted at FB settings page. 
When clicked on Log In there will be error like " ..this URL isnt allowed at config ...". When URL matched, proper FB login would appear.

**Comment by vyotov** [comment]
I have an error in the dev console 
`Error: Cannot find module "!!./../../../node_modules/css-loader/index.js!./../../../node_modules/less-loader/index.js!./main.less"
webpackMissingModule()
 bundle.js:60297
<anonymous>
 bundle.js:60297
__webpack_require__()
 bundle.js:20
<anonymous>
 bundle.js:74
__webpack_require__()
 bundle.js:20
<anonymous>
 bundle.js:49
__webpack_require__()
 bundle.js:20
<anonymous>
 bundle.js:40
<anonymous>
 bundle.js:1
 bundle.js:60297:80`
