### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by julianzuijdwegt** [sqren/fb-sleep-stats#39]
How change xs, appid and c_user?

**Comment by sorenlouv** [comment]
Did you copy `config/default.json` to `config/development.json` ?

**Comment by julianzuijdwegt** [comment]
Yes but after that you have tot change the value, how can i do this?

**Comment by julianzuijdwegt** [comment]
How van i do this*

**Comment by julianzuijdwegt** [comment]
How can i do this*

**Comment by nikkihas** [comment]
Open the document with any kind of text editor. You'll find the c_user and xs whereafter it shows " ". Put the right values in between the quotation marks.

**Comment by julianzuijdwegt** [comment]
Which document i have to change? where can i find it?

**Comment by sorenlouv** [comment]
Open `config/development.json` with a text editor (eg. Notepad or SublimeText) and update the values.
