### ISSUE TITLE
"npm run webpack" error

### ISSUE THREAD

**Issue by ugurhant** [sqren/fb-sleep-stats#40]
I get an error when running "npm run webpack"

I tried `rm -rf node_modules
npm install
npm run webpack`

But 

```
rm -rf node_modules
rm is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sorenlouv** [comment]
The first time you install, you don't have to `rm -rf node_modules`. (it's for removing the folder)
Every line is an independent command, and should be executed one-by-one.

**Comment by ugurhant** [comment]
I know. I installed once. But get an error when i wrote "npm run webpack". For this i try rm -rf node_modules but rm is not recognized. I am noob for node.js

edit: i am sorry. i pressed space button.

**Comment by sorenlouv** [comment]
What error did you get, when running `npm run webpack`? What version of Node do you have?

**Comment by sorenlouv** [comment]
It sounds like `rm' is not available (which is a unix command). Try installing cygwin.
