### ISSUE TITLE
Elaborate on a few steps please

### ISSUE THREAD

**Issue by nikkihas** [sqren/fb-sleep-stats#41]
Hi Søren, thank you for releasing this. It's a great way of showing how public our data is in contrary to talking or discussing it.

I would like to ask you (or somebody else) if you could elaborate on the steps "Install dependencies", "Build browser dependencies" and "Starting" section. I don't know what to do at these steps. I am using Mac OS X and not experienced with programming in this way although I am super excited to see my friends sleeping patterns and confronting them with it!

I hope to be able to run this soon too.

Kind regards,

Nikki

**Comment by sorenlouv** [comment]
Hi @nikkihas 
I've updated the readme with links for how to install Git and Node:
- Git ([how to install](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git))
- Node.js ([how to install](https://docs.npmjs.com/getting-started/installing-node))

I'd like to keep the readme relatively short. What issues are you encountering?

**Comment by nikkihas** [comment]
Thank you for your quick reply, the added links helped me to figure it out. I've been collecting people their data for a while now, yet when I type "npm start" in Terminal it doesn't give me anything, it does nothing. This is probably why my http://localhost:3000/ is not showing anything. How can I retrieve data in my localhost?

**Comment by nikkihas** [comment]
I've disabled AdBlocker and it is showing active users every 600 seconds.

**Comment by nikkihas** [comment]
While one terminal window runs to look for active users, another window executed npm start whereafter I can look at the result on localhost:3000. I did not know I needed to execute npm start in a new window.

**Comment by sorenlouv** [comment]
I've updated the readme to reflect that
