### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by likoros123** [sqren/fb-sleep-stats#42]
Hi guys, this is my npm-debug.log ,
i have a problem with it. Thanks for help.

```
0 info it worked if it ends with ok

1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',

1 verbose cli   'run',

1 verbose cli   'scrape' ]

2 info using npm@2.14.12

3 info using node@v4.3.1

4 verbose config Skipping project config: C:\Users\Jablíčkář/.npmrc. (matches userconfig)

5 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Jablíčkář\package.json'

5 verbose stack     at Error (native)

6 verbose cwd C:\Users\Jablíčkář

7 error Windows_NT 10.0.10586

8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program 

Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "scrape"

9 error node v4.3.1

10 error npm  v2.14.12

11 error path C:\Users\Jablíčkář\package.json

12 error code ENOENT

13 error errno -4058

14 error syscall open

15 error enoent ENOENT: no such file or directory, open 'C:\Users\Jablíčkář\package.json'

15 error enoent This is most likely not a problem with npm itself

15 error enoent and is related to npm not being able to find a file.

16 verbose exit [ -4058, true ]
```

**Comment by sorenlouv** [comment]
What lead up to this? Did you clone the repository? Did you cd into the folder? Did you run npm install?
Please follow the readme step-by-step and let us know at what step the error occurs, and what is says.

**Comment by likoros123** [comment]
I thought i did it but now got new problem. While i type npm run scrape, i get this message: 

node ./scrape.js

Polling every 600 seconds

An error occured in buddyList [TypeError: Cannot read property "0" of undefined]

_date_ An error occured while scraping. Please check to make sure your development.json config is

correct [TypeError: Cannot read property "1" of null] 

What does it mean?

And on web:  
http://imgur.com/4bcCkdn

**Comment by sorenlouv** [comment]
Did you follow the [readme](https://github.com/sqren/fb-sleep-stats/blob/master/README.md) and update the values in development.json?

**Comment by likoros123** [comment]
[https://ctrlv.cz/6et9](url)

**Comment by likoros123** [comment]
![](https://ctrlv.cz/shots/2016/03/03/6et9.png)

**Comment by sorenlouv** [comment]
> There's no cp in windows... it's copy. cp is for Linux.
> 
> You can, however, use cp from Windows prompt if you have Cygwin installed. And it also has rsync, which is a far more complete tool if you're not just copying one file around (e.g. backup purposes).

http://stackoverflow.com/a/21734429/434980

**Comment by likoros123** [comment]
i just go over this step and it works. (i rewrote default.json )
