### ISSUE TITLE
Can't remove on windows

### ISSUE THREAD

**Issue by mihailivanchev** [sqren/fb-sleep-stats#43]
There is no easy way to remove this on windows. So many folders with such long names, makes them unable for windows to read them, so once installed, you have to rename or move every folder to be able to delete.

**Comment by Benj4** [comment]
only removes the "fb-sleep-stats" folder.
Node.js and git are third-party programs that can uninstall like any other program

**Comment by mihailivanchev** [comment]
What are you talking about?! node.js files are not in the same folder. I am talking about the files you get when you clone the repository... They are undeletable in windows. I had to boot my ubuntu installation to get rid of them.

**Comment by Benj4** [comment]
sounds like a problem of windows, I deleted it without problems (window x64)

**Comment by sorenlouv** [comment]
I'll close this for now. Please let me know if you have additional issues.
