### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by tso8882000** [sqren/fb-sleep-stats#44]
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai                                                      l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl                                                      e.

> history@2.0.0 postinstall C:\Users\tso\Desktop\fb-sleep-stats\node_modules\his                                                      tory
> node ./npm-scripts/postinstall.js
> 
> react-router@2.0.0 postinstall C:\Users\tso\Desktop\fb-sleep-stats\node_module                                                      s\react-router
> node ./npm-scripts/postinstall.js

fb-sleep-stats@0.9.0 C:\Users\tso\Desktop\fb-sleep-stats
+-- babel-core@6.5.2
| +-- babel-code-frame@6.5.0
| | +-- chalk@1.1.1
| | | +-- ansi-styles@2.2.0
| | | | `-- color-convert@1.0.0
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | |`-- ansi-regex@2.0.0
| | | +-- strip-ansi@3.0.1
| | | `-- supports-color@2.0.0
| | +-- esutils@2.0.2
| | +-- js-tokens@1.0.2
| | +-- line-numbers@0.2.0
| | |`-- left-pad@0.0.3
| | `-- repeating@1.1.3
| |`-- is-finite@1.0.1
| |     `-- number-is-nan@1.0.0
| +-- babel-generator@6.5.0
| | +-- detect-indent@3.0.1
| | | +-- get-stdin@4.0.1
| | |`-- minimist@1.2.0
| | +-- is-integer@1.0.6
| | +-- lodash@3.10.1
| | +-- source-map@0.5.3
| | `-- trim-right@1.0.1
| +-- babel-helpers@6.5.0
| +-- babel-messages@6.5.0
| +-- babel-register@6.5.2
| | +-- core-js@1.2.6
| | +-- home-or-tmp@1.0.0
| | | +-- os-tmpdir@1.0.1
| | |`-- user-home@1.1.1
| | +-- lodash@3.10.1
| | `-- source-map-support@0.2.10
| |`-- source-map@0.1.32
| +-- babel-runtime@5.8.35
| +-- babel-template@6.5.0
| | `-- lodash@3.10.1
| +-- babel-traverse@6.5.0
| | +-- globals@8.18.0
| |`-- lodash@3.10.1
| +-- babel-types@6.5.2
| | +-- lodash@3.10.1
| | `-- to-fast-properties@1.0.1
| +-- babylon@6.5.2
| +-- convert-source-map@1.2.0
| +-- debug@2.2.0
| |`-- ms@0.7.1
| +-- json5@0.4.0
| +-- lodash@3.10.1
| +-- minimatch@2.0.10
| | `-- brace-expansion@1.1.3
| |   +-- balanced-match@0.3.0
| |`-- concat-map@0.0.1
| +-- path-exists@1.0.0
| +-- path-is-absolute@1.0.0
| +-- private@0.1.6
| +-- shebang-regex@1.0.0
| +-- slash@1.0.0
| `-- source-map@0.5.3
+-- babel-loader@6.2.3
| +-- loader-utils@0.2.12
| |`-- big.js@3.1.3
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
|`-- object-assign@4.0.1
+-- babel-preset-es2015@6.5.0
| +-- babel-plugin-check-es2015-constants@6.5.0
| +-- babel-plugin-transform-es2015-arrow-functions@6.5.2
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.5.0
| +-- babel-plugin-transform-es2015-block-scoping@6.5.0
| | `-- lodash@3.10.1
| +-- babel-plugin-transform-es2015-classes@6.5.2
| | +-- babel-helper-define-map@6.5.0
| | |`-- lodash@3.10.1
| | +-- babel-helper-function-name@6.5.0
| | +-- babel-helper-optimise-call-expression@6.5.0
| | `-- babel-helper-replace-supers@6.5.0
| +-- babel-plugin-transform-es2015-computed-properties@6.5.2
| +-- babel-plugin-transform-es2015-destructuring@6.5.0
| +-- babel-plugin-transform-es2015-for-of@6.5.2
| +-- babel-plugin-transform-es2015-function-name@6.5.0
| +-- babel-plugin-transform-es2015-literals@6.5.0
| +-- babel-plugin-transform-es2015-modules-commonjs@6.5.2
| |`-- babel-plugin-transform-strict-mode@6.5.2
| +-- babel-plugin-transform-es2015-object-super@6.5.0
| +-- babel-plugin-transform-es2015-parameters@6.5.0
| | +-- babel-helper-call-delegate@6.5.0
| | | `-- babel-helper-hoist-variables@6.5.0
| |`-- babel-helper-get-function-arity@6.5.0
| +-- babel-plugin-transform-es2015-shorthand-properties@6.5.0
| +-- babel-plugin-transform-es2015-spread@6.5.2
| +-- babel-plugin-transform-es2015-sticky-regex@6.5.0
| | `-- babel-helper-regex@6.5.0
| |`-- lodash@3.10.1
| +-- babel-plugin-transform-es2015-template-literals@6.5.2
| +-- babel-plugin-transform-es2015-typeof-symbol@6.5.0
| +-- babel-plugin-transform-es2015-unicode-regex@6.5.0
| | `-- regexpu-core@1.0.0
| |   +-- regenerate@1.2.1
| |   +-- regjsgen@0.2.0
| |`-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
|`-- babel-plugin-transform-regenerator@6.5.2
|   `-- babel-plugin-syntax-async-functions@6.5.0
+-- babel-preset-react@6.5.0
| +-- babel-plugin-syntax-flow@6.5.0
| +-- babel-plugin-syntax-jsx@6.5.0
| +-- babel-plugin-transform-flow-strip-types@6.5.0
| +-- babel-plugin-transform-react-display-name@6.5.0
| +-- babel-plugin-transform-react-jsx@6.5.2
| |`-- babel-helper-builder-react-jsx@6.5.0
| |   `-- lodash@3.10.1
|`-- babel-plugin-transform-react-jsx-source@6.5.0
+-- bluebird@3.3.3
+-- config@1.19.0
+-- cookie-parser@1.4.1
| +-- cookie@0.2.3
| `-- cookie-signature@1.0.6
+-- css-loader@0.23.1
| +-- css-selector-tokenizer@0.5.4
| | +-- cssesc@0.1.0
| |`-- fastparse@1.1.1
| +-- cssnano@3.5.2
| | +-- autoprefixer@6.3.3
| | | +-- browserslist@1.1.3
| | | +-- caniuse-db@1.0.30000414
| | | +-- normalize-range@0.1.2
| | | `-- num2fraction@1.2.2
| | +-- decamelize@1.1.2
| | +-- defined@1.0.0
| | +-- indexes-of@1.0.1
| | +-- postcss-calc@5.2.0
| | | +-- postcss-message-helpers@2.0.0
| | |`-- reduce-css-calc@1.2.1
| | |   +-- balanced-match@0.1.0
| | |   `-- reduce-function-call@1.0.1
| | |`-- balanced-match@0.1.0
| | +-- postcss-colormin@2.1.8
| | | `-- colormin@1.0.7
| | |   +-- color@0.11.1
| | |   | +-- color-convert@0.5.3
| | |   |`-- color-string@0.3.0
| | |   |   `-- color-name@1.1.1
| | |`-- css-color-names@0.0.3
| | +-- postcss-convert-values@2.3.4
| | +-- postcss-discard-comments@2.0.4
| | +-- postcss-discard-duplicates@2.0.1
| | +-- postcss-discard-empty@2.0.1
| | +-- postcss-discard-unused@2.2.1
| | | +-- flatten@1.0.2
| | | `-- uniqs@2.0.0
| | +-- postcss-filter-plugins@2.0.0
| | |`-- uniqid@1.0.0
| | +-- postcss-merge-idents@2.1.5
| | | `-- has-own@1.0.0
| | +-- postcss-merge-longhand@2.0.1
| | +-- postcss-merge-rules@2.0.6
| | +-- postcss-minify-font-values@1.0.3
| | +-- postcss-minify-gradients@1.0.1
| | +-- postcss-minify-params@1.0.4
| | |`-- alphanum-sort@1.0.2
| | +-- postcss-minify-selectors@2.0.4
| | | `-- postcss-selector-parser@1.3.2
| | |`-- uniq@1.0.1
| | +-- postcss-normalize-charset@1.1.0
| | +-- postcss-normalize-url@3.0.7
| | | +-- is-absolute-url@2.0.0
| | | `-- normalize-url@1.4.1
| | |   +-- prepend-http@1.0.3
| | |`-- sort-keys@1.1.1
| | |     `-- is-plain-obj@1.1.0
| | +-- postcss-ordered-values@2.1.0
| | +-- postcss-reduce-idents@2.3.0
| | +-- postcss-reduce-transforms@1.0.3
| | +-- postcss-svgo@2.1.2
| | | +-- is-svg@1.1.1
| | |`-- svgo@0.6.1
| | |   +-- coa@1.0.1
| | |   | `-- q@1.4.1
| | |   +-- colors@1.1.2
| | |   +-- csso@1.4.4
| | |   |`-- clap@1.0.10
| | |   +-- js-yaml@3.4.6
| | |   | +-- argparse@1.0.6
| | |   | | `-- sprintf-js@1.0.3
| | |   |`-- inherit@2.2.3
| | |   `-- whet.extend@0.9.9
| | +-- postcss-unique-selectors@2.0.2
| | +-- postcss-value-parser@3.3.0
| |`-- postcss-zindex@2.0.1
| +-- lodash.camelcase@3.0.1
| | `-- lodash._createcompounder@3.0.0
| |   +-- lodash.deburr@3.2.0
| |   |`-- lodash._root@3.0.1
| |   `-- lodash.words@3.2.0
| +-- postcss@5.0.18
| | +-- js-base64@2.1.9
| | +-- source-map@0.5.3
| |`-- supports-color@3.1.2
| +-- postcss-modules-extract-imports@1.0.0
| +-- postcss-modules-local-by-default@1.0.1
| +-- postcss-modules-scope@1.0.0
| +-- postcss-modules-values@1.1.1
| | `-- icss-replace-symbols@1.0.2
|`-- source-list-map@0.1.5
+-- eslint-plugin-react@4.1.0
+-- express@4.13.4
| +-- accepts@1.2.13
| | +-- mime-types@2.1.10
| | | `-- mime-db@1.22.0
| |`-- negotiator@0.5.3
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.1
| +-- content-type@1.0.1
| +-- cookie@0.1.5
| +-- depd@1.1.0
| +-- escape-html@1.0.3
| +-- etag@1.7.0
| +-- finalhandler@0.4.1
| | `-- unpipe@1.0.0
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- on-finished@2.3.0
| |`-- ee-first@1.1.1
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@1.0.10
| | +-- forwarded@0.1.0
| | `-- ipaddr.js@1.0.5
| +-- qs@4.0.0
| +-- range-parser@1.0.3
| +-- send@0.13.1
| | +-- destroy@1.0.4
| | +-- http-errors@1.3.1
| |`-- statuses@1.2.1
| +-- serve-static@1.10.2
| +-- type-is@1.6.12
| | `-- media-typer@0.3.0
| +-- utils-merge@1.0.0
|`-- vary@1.0.1
+-- fb-sleep@2.2.0
| +-- bluebird@3.3.1
| +-- cheerio@0.20.0
| | +-- css-select@1.2.0
| | | +-- boolbase@1.0.0
| | | +-- css-what@2.1.0
| | | +-- domutils@1.5.1
| | | `-- nth-check@1.0.1
| | +-- dom-serializer@0.1.0
| | |`-- domelementtype@1.1.3
| | +-- entities@1.1.1
| | +-- htmlparser2@3.8.3
| | | +-- domelementtype@1.3.0
| | | +-- domhandler@2.3.0
| | | `-- entities@1.0.0
| |`-- jsdom@7.2.2
| |   +-- abab@1.0.3
| |   +-- acorn@2.7.0
| |   +-- acorn-globals@1.0.9
| |   +-- cssom@0.3.1
| |   +-- cssstyle@0.2.34
| |   +-- escodegen@1.8.0
| |   | +-- estraverse@1.9.3
| |   | +-- optionator@0.8.1
| |   | | +-- deep-is@0.1.3
| |   | | +-- fast-levenshtein@1.1.3
| |   | | +-- levn@0.3.0
| |   | | +-- prelude-ls@1.1.2
| |   | | +-- type-check@0.3.2
| |   | | `-- wordwrap@1.0.0
| |   |`-- source-map@0.2.0
| |   +-- nwmatcher@1.3.7
| |   +-- parse5@1.5.1
| |   +-- sax@1.1.5
| |   +-- symbol-tree@3.1.4
| |   +-- webidl-conversions@2.0.1
| |   +-- whatwg-url-compat@0.6.5
| |   | `-- tr46@0.0.3
| |`-- xml-name-validator@2.0.1
| `-- request-promise@1.0.2
|   +-- bluebird@2.10.2
|   +-- cls-bluebird@1.0.1
|   |`-- shimmer@1.1.0
|   +-- UNMET PEER DEPENDENCY continuation-local-storage@~3
|   `-- lodash@3.10.1
+-- less@2.6.0
| +-- errno@0.1.4
| |`-- prr@0.0.0
| +-- graceful-fs@3.0.8
| +-- image-size@0.3.5
| +-- mime@1.3.4
| +-- promise@6.1.0
| | `-- asap@1.0.0
| +-- request@2.69.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.2.1
| | |`-- lru-cache@2.7.3
| | +-- bl@1.0.3
| | | `-- readable-stream@2.0.5
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | |`-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.0-rc3
| | +-- har-validator@2.0.6
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | +-- is-my-json-valid@2.13.1
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | |`-- is-property@1.0.2
| | | | +-- jsonpointer@2.0.0
| | | | `-- xtend@4.0.1
| | |`-- pinkie-promise@2.0.0
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | |`-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.2.2
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.2
| | | | `-- verror@1.3.6
| | |`-- sshpk@1.7.4
| | |   +-- asn1@0.2.3
| | |   +-- dashdash@1.13.0
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |`-- tweetnacl@0.14.1
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.1
| | +-- qs@6.0.2
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.2.1
| | `-- tunnel-agent@0.4.2
|`-- source-map@0.4.4
|   `-- amdefine@1.0.0
+-- less-loader@2.2.2
+-- lodash@4.5.1
+-- lowdb@0.12.4
| +-- graceful-fs@4.1.3
| +-- is-promise@2.1.0
| +-- json-parse-helpfulerror@1.0.3
| |`-- jju@1.3.0
| `-- steno@0.4.3
+-- moment@2.11.2
+-- react@0.14.7
| +-- envify@3.4.0
| | +-- jstransform@10.1.0
| | | +-- base62@0.1.1
| | | +-- esprima-fb@13001.1001.0-dev-harmony-fb
| | |`-- source-map@0.1.31
| | `-- through@2.3.8
|`-- fbjs@0.6.1
|   +-- loose-envify@1.1.0
|   +-- promise@7.1.1
|   | `-- asap@2.0.3
|   +-- ua-parser-js@0.7.10
|`-- whatwg-fetch@0.9.0
+-- react-dom@0.14.7
+-- react-highcharts@7.0.0
| `-- highcharts@4.2.3
+-- react-router@2.0.0
| +-- history@2.0.0
| | +-- deep-equal@1.0.1
| |`-- query-string@3.0.1
| |   `-- strict-uri-encode@1.1.0
| +-- invariant@2.2.0
|`-- warning@2.1.0
+-- request-promise@2.0.1
| `-- bluebird@2.10.2
+-- style-loader@0.13.0
+-- superagent@1.6.1
| +-- component-emitter@1.1.2
| +-- cookiejar@2.0.6
| +-- extend@1.2.1
| +-- form-data@0.2.0
| | +-- async@0.9.2
| | +-- combined-stream@0.0.7
| | |`-- delayed-stream@0.0.5
| | `-- mime-types@2.0.14
| |`-- mime-db@1.12.0
| +-- formidable@1.0.14
| +-- methods@1.0.1
| +-- qs@2.3.3
| +-- readable-stream@1.0.27-1
| | +-- core-util-is@1.0.2
| | +-- inherits@2.0.1
| | +-- isarray@0.0.1
| | `-- string_decoder@0.10.31
|`-- reduce-component@1.0.1
`-- webpack@1.12.14
  +-- async@1.5.2
  +-- clone@1.0.2
  +-- enhanced-resolve@0.9.1
  |`-- memory-fs@0.2.0
  +-- esprima@2.7.2
  +-- interpret@0.6.6
  +-- memory-fs@0.3.0
  | `-- readable-stream@2.0.5
  |   +-- process-nextick-args@1.0.6
  |`-- util-deprecate@1.0.2
  +-- node-libs-browser@0.5.3
  | +-- assert@1.3.0
  | +-- browserify-zlib@0.1.4
  | | `-- pako@0.2.8
  | +-- buffer@3.6.0
  | | +-- base64-js@0.0.8
  | | +-- ieee754@1.1.6
  | |`-- isarray@1.0.0
  | +-- console-browserify@1.1.0
  | | `-- date-now@0.1.4
  | +-- constants-browserify@0.0.1
  | +-- crypto-browserify@3.2.8
  | | +-- pbkdf2-compat@2.0.1
  | | +-- ripemd160@0.2.0
  | |`-- sha.js@2.2.6
  | +-- domain-browser@1.1.7
  | +-- events@1.1.0
  | +-- http-browserify@1.7.0
  | | `-- Base64@0.2.1
  | +-- https-browserify@0.0.0
  | +-- os-browserify@0.1.2
  | +-- path-browserify@0.0.0
  | +-- process@0.11.2
  | +-- punycode@1.4.0
  | +-- querystring-es3@0.2.1
  | +-- readable-stream@1.1.13
  | +-- stream-browserify@1.0.0
  | +-- timers-browserify@1.4.2
  | +-- tty-browserify@0.0.0
  | +-- url@0.10.3
  | | +-- punycode@1.3.2
  | |`-- querystring@0.2.0
  | +-- util@0.10.3
  | `-- vm-browserify@0.0.4
  |`-- indexof@0.0.1
  +-- optimist@0.6.1
  | +-- minimist@0.0.10
  | `-- wordwrap@0.0.3
  +-- supports-color@3.1.2
  |`-- has-flag@1.0.0
  +-- tapable@0.1.10
  +-- uglify-js@2.6.2
  | +-- async@0.2.10
  | +-- source-map@0.5.3
  | +-- uglify-to-browserify@1.0.2
  | `-- yargs@3.10.0
  |   +-- camelcase@1.2.1
  |   +-- cliui@2.1.0
  |   | +-- center-align@0.1.3
  |   | | +-- align-text@0.1.4
  |   | | | +-- longest@1.0.1
  |   | | |`-- repeat-string@1.5.4
  |   | | `-- lazy-cache@1.0.3
  |   | +-- right-align@0.1.3
  |   |`-- wordwrap@0.0.2
  |   `-- window-size@0.1.0
  +-- watchpack@0.2.9
  | +-- async@0.9.2
  |`-- chokidar@1.4.3
  |   +-- anymatch@1.3.0
  |   | +-- arrify@1.0.1
  |   | `-- micromatch@2.3.7
  |   |   +-- arr-diff@2.0.0
  |   |   |`-- arr-flatten@1.0.1
  |   |   +-- array-unique@0.2.1
  |   |   +-- braces@1.8.3
  |   |   | +-- expand-range@1.8.1
  |   |   | | `-- fill-range@2.2.3
  |   |   | |   +-- is-number@2.1.0
  |   |   | |   +-- isobject@2.0.0
  |   |   | |`-- randomatic@1.1.5
  |   |   | +-- preserve@0.2.0
  |   |   | `-- repeat-element@1.1.2
  |   |   +-- expand-brackets@0.1.4
  |   |   +-- extglob@0.3.2
  |   |   +-- filename-regex@2.0.0
  |   |   +-- kind-of@3.0.2
  |   |   |`-- is-buffer@1.1.2
  |   |   +-- normalize-path@2.0.1
  |   |   +-- object.omit@2.0.0
  |   |   | +-- for-own@0.1.3
  |   |   | | `-- for-in@0.1.4
  |   |   |`-- is-extendable@0.1.1
  |   |   +-- parse-glob@3.0.4
  |   |   | +-- glob-base@0.3.0
  |   |   | `-- is-dotfile@1.0.2
  |   |`-- regex-cache@0.4.2
  |   |     +-- is-equal-shallow@0.1.3
  |   |     `-- is-primitive@2.0.0
  |   +-- async-each@1.0.0
  |   +-- glob-parent@2.0.0
  |   +-- is-binary-path@1.0.1
  |   |`-- binary-extensions@1.4.0
  |   +-- is-glob@2.0.1
  |   | `-- is-extglob@1.0.0
  |`-- readdirp@2.0.0
  |     `-- readable-stream@2.0.5
`-- webpack-core@0.6.8
    `-- source-map@0.4.4

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve                                                      nts@1.0.8
npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but                                                       none was installed.

> I dont know what to do

**Comment by canvural** [comment]
Thats just a warning you can ignore it. It should work normally.

**Comment by sorenlouv** [comment]
@tso8882000 can this issue be closed?
