### ISSUE TITLE
not possible to run mpn install

### ISSUE THREAD

**Issue by sakonn** [sqren/fb-sleep-stats#45]
I'm going step by step but I can't run npm install. Is there something I'm missing?? 
![2016-02-29 18_44_56-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/17552397/13403347/d1e92c2e-df14-11e5-9c54-a4bf5f050fd9.jpg)

I've installed nodejs from official site.

**Comment by sorenlouv** [comment]
It sounds like npm is not (properly) installed. npm is bundled with the latest version nodejs, so if you've installed that, it should work.

**Comment by Benj4** [comment]
try to run "npm install" from the git console, or from the console nodejs, NOT from cmd

**Comment by sakonn** [comment]
@Benj4 thanks for help. Running npm install from the git console helped.
