### ISSUE TITLE
Updating values

### ISSUE THREAD

**Issue by pedropabloq21** [sqren/fb-sleep-stats#46]
Hi, I have some problems updating the values because it´s the first thime i use Git

Could you type the code whit blank spaces to paste my information?

Thanks

**Comment by Benj4** [comment]
which values ​​refer ?. c_user and xs in the config file can be edited with any text editor

**Comment by pedropabloq21** [comment]
Thanks, i did it :)

Now I have problmes with scraping,

![image](https://cloud.githubusercontent.com/assets/10394688/13452896/1eb7abd8-e01a-11e5-9945-aa228f523b77.png)
