### ISSUE TITLE
For those looking to start this...

### ISSUE THREAD

**Issue by samdesota** [sqren/fb-sleep-stats#5]
Couple of extra steps.
1. You need to create a new Facebook app with `http://localhost:3000` added to the domains.
2. Change the `appId` inside src/browser/services/facebook.js to the newly created appId
3. To start the server, run `npm run build-minified` before starting the server. You can also run `forever-scrape` and `forever-server` for a more permanent solution.

**Comment by girlluvzermac** [comment]
Perfect, thank you!

**Comment by chhabs** [comment]
Fixed it for me. Thanks

**Comment by shernshiou** [comment]
it would be nice if we can change the appId at config file.

**Comment by marekceglowski** [comment]
Cool thanks!

**Comment by turlockmike** [comment]
Made a pull request to fix this more permanently.

**Comment by MaffooBristol** [comment]
How are we meant to add localhost to allowed URLs? It seems to say it's not an acceptable address...

**Comment by YeomansIII** [comment]
@MaffooBristol Make sure you include http:// although I did this and I still get the error 

```
Could not get users: Cannot read property '1' of null undefined
```

**Comment by MaffooBristol** [comment]
Yeah I ended up following [this](http://stackoverflow.com/questions/21295872/facebook-app-localhost-no-longer-works-as-app-domain) and got my localhost added, but I get that exact same error you did, @YeomansIII

**Comment by YeomansIII** [comment]
@MaffooBristol You need to use your numeric Facebook ID.  You can find it as the c_user cookie at the same place you found the xs token

**Comment by MaffooBristol** [comment]
@YeomansIII Ahhh, that works. I was using the "fbid" param I got from the URL when looking at my own profile pic (vain, I know, eh? ;) )

Does the job, cheers.
