### ISSUE TITLE
Problem with displaying the info... january january january

### ISSUE THREAD

**Issue by magicus1** [sqren/fb-sleep-stats#52]
I got it up and running, but after awhile only this was displayed... as you can see it says january all the time on the graph...

What went wrong here?

![image](https://cloud.githubusercontent.com/assets/17537183/13426877/b7f67442-dfb0-11e5-8e97-431e73cdfede.png)

**Comment by canvural** [comment]
See #48

**Comment by magicus1** [comment]
Ok thx. Is there a smart way to delete the 0's in the file? I have too many contacts to do it manually

**Comment by sorenlouv** [comment]
I'm not able to reproduce this myself at the moment. Can you walk me through how this happened?

**Comment by magicus1** [comment]
Im not sure how it happend. But at first it just happend when I checked a few of my contacts, but the other ones were working fine. Now every single contact i check has this january january problem.

**Comment by magicus1** [comment]
Now I found the function search and replace and I deleted all the entries with " 0 " and replaced it with a space, but i still have same problem.. The file I should edit is db.json right?

**Comment by nick-potts** [comment]
in /src/server/services. I removed all entries that had just a zero and removed the line containing the zero for all entries with other data. The regex for it wasn't fun however and it would have almost been faster to go through by hand and fix it.

**Comment by magicus1** [comment]
Alright. So when I edited the file to delete the entries with only a zero the program collapsed:
![image](https://cloud.githubusercontent.com/assets/17537183/13452411/ca085244-e047-11e5-88f9-61891b93aced.png)
But when I restored the original file, the program was working again. 

Here is an exert of my db.json file:
![image](https://cloud.githubusercontent.com/assets/17537183/13452460/381645b6-e048-11e5-84a7-3941dde9f6f9.png)

Now those 3 zero's at the end shouldnt be there right? And neither should the single 0 be. So my solution is to go into notepad and search and replace all single 0's + 000 with a empty space. Does that sound about right?

**Comment by magicus1** [comment]
So I tried that and here is a new exert of how the db.json file looks, but still the data is displayed in the same way with january january etc.
![image](https://cloud.githubusercontent.com/assets/17537183/13452888/58604584-e04c-11e5-98ef-93e3dc087445.png)

Perhaps I should restart "npm start"?

**Comment by sorenlouv** [comment]
A javascript timestamp is milliseconds since 1970, and 13 chars long. So don't remove the 3 zeroes in the end. 
I don't know why you are getting the timestamps of "0". That must be a bug.

**Comment by magicus1** [comment]
i works! I had to search and replace for something like:    "     0,"

**Comment by jduncanator** [comment]
@sqren From what I can tell you can get times of "0" when Facebook rate limits your requests to the endpoint that dishes out friend activity. I managed to encounter this by setting my scrape interval down to 60 seconds (thinking that it would all just magically work) only to find out that Facebook rate limit you (and return wacky data) if you scrape too often. It appears that this managed to introduce, at least in my instance, 0's into the data.
