### ISSUE TITLE
How is the time considered?

### ISSUE THREAD

**Issue by Oooz** [sqren/fb-sleep-stats#55]
When it uptades (every 10 minutes), does it only see if the user is "active or not" or it also sees how long the user has been away (x minutes ago for ex)?

Thanks

**Comment by canvural** [comment]
Every ten minutes it checks who is online right now.

**Comment by Oooz** [comment]
Don't you think that considering the away time would yield a more accurate result?

**Comment by canvural** [comment]
What do you mean by that? How can you consider it?

You can see the away times in the graph. The little gaps represents the time they are not online.

**Comment by Oooz** [comment]
[May be it already has this features, probably my fault... however:)

I mean that in order to the script catch you, you must be online/active in that specific moment of the script update. In other words, if you go online for 5 minutes in between 2 scripts update, it is the same as not going online/active. IF the script could also capture the AWAY time that Facebook Chat also provide, the graphs and sleep time woud be more accurate.

As in the image above; If that first contact made a unique facebook log in during the whole day AND between 2 scripts checks (in a period smaller than 10 minutes), than he would not had been logged as active.

If I could use this information (5m ago), it wouldnt be necessary to increase the uptade rate (and avoid Facebook's blocking (dunno if its common) and guarantee one more information to increase the script's accuracy.

![ex](https://cloud.githubusercontent.com/assets/17578371/13447738/8ec579b4-dffc-11e5-8970-532249ad7d4f.gif)

**Comment by sorenlouv** [comment]
> When it uptades (every 10 minutes), does it only see if the user is "active or not"

No, we see _when_ they were last online (as in, the exact time eg. 10:34AM on Monday)

> [does] it also sees how long the user has been away (x minutes ago for ex)?

We can calculate the time between now and when they were last online, and thus get how long they have been away.

**Comment by sorenlouv** [comment]
I believe this issue can be closed. Let me know if there is anything else.
