### ISSUE TITLE
An error occured while scraping. [TypeError: Cannot read property '1' of null]

### ISSUE THREAD

**Issue by persundman** [sqren/fb-sleep-stats#56]
I get this error while running An error occured while scraping. 
An error occured in buddyList { [StatusCodeError: 500 - ]
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - ',
.....
Please check to make sure your development.json config is correct [TypeError: Cannot read property '1' of null]

I have checked the development.json config but it looks OK.

Any clues?

**Comment by Lawlietr** [comment]
Same problem too

any ideas?

**Comment by pedropabloq21** [comment]
same problem

please :(

**Comment by Newtonishappy** [comment]
Yep ! same for me ! 
So I guess that's why I have nothing to show in my localhost:300 

If you have any solution to that :)

**Comment by alexandreadis** [comment]
same for me!!

**Comment by vyotov** [comment]
I had the same issue. 
I manage to fix it, check your fb id - > "c_user" in developer.json 
first i got it as a letters and numbers but it need to be only number use   [this link ](http://findmyfbid.com/) to check yours

**Comment by Newtonishappy** [comment]
Yes !! problem solved for me !

**Comment by njharbo** [comment]
Had the same problem, and this solved it. Thanks!

**Comment by persundman** [comment]
Great! Problem solved. Thanks!
