### ISSUE TITLE
npm run scrape error

### ISSUE THREAD

**Issue by hanxiang1208** [sqren/fb-sleep-stats#59]
no idea what is going on.... something missing maybe...
i am not good with computer.. ><
![npm](https://cloud.githubusercontent.com/assets/10303291/13464893/22f173b4-e0ce-11e5-803d-4729fe24f37c.jpg)

**Comment by canvural** [comment]
You are not in the right folder. cd into the project folder. Or maybe you didn't clone it at all. Use git clone to download it to your computer.

**Comment by sorenlouv** [comment]
Please follow the [readme](https://github.com/sqren/fb-sleep-stats/blob/master/README.md)

**Comment by hanxiang1208** [comment]
problem solved by cd into the project folder. Thanks canvural! :)
