### ISSUE TITLE
Running the program again

### ISSUE THREAD

**Issue by kosi96** [sqren/fb-sleep-stats#61]
Hello!

I'm new to github so it will sound as a really dumb question. 
I have managed to run the program and it works perfectly ( I have opened two githube consoles.).
I understand that if I shut down my PC there will be no scraping, and data will be missing. But if I accidentally do. How can I run the program again? Do I have to do every step from the beginning?

**Comment by canvural** [comment]
No, you just run `npm run scrape` again.

**Comment by sorenlouv** [comment]
@canvural thanks for helping out. 
Remember: you must execute the commands from inside the fb-sleep-stats folder.
