### ISSUE TITLE
saved data and resume polling step

### ISSUE THREAD

**Issue by hanxiang1208** [sqren/fb-sleep-stats#62]
hi, would like to know if i stop polling the data, where it will be saved? btw, when i resume my tracking, just get the things started from "npm run scrape" and "npm start" in 2 different consoles? the old saved data will automatically cumulative with the new data recorded when i start it again? i mean i dont need to start from scrap and wait about 24 hours to get the sleeping data table tabulated.

**Comment by canvural** [comment]
Its saved to a json file located at `src/server/services/db.json`.

And yeah you will be able to see the old data when you resume. You don't have to wait. New data will be added over to it.

**Comment by sorenlouv** [comment]
I'll close this issue for now. Let me know if you continue experiencing issues.
