### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arno1234** [sqren/fb-sleep-stats#63]
Hello,

Since tomorrow morning I got this error:

Polling every 600 seconds
An error occured in buddyList [TypeError: Cannot read property '0' of undefined]
3/3/2016, 1:51:23 PM An error occured while scraping. Please check to make sure your development.json config is correct [TypeError: Cannot read property '1' of null]

Any idea what is going wrong. I used to work verry good.

Config file:
{
    "fbCookie": {
    "c_user": "000000000000",
        "xs": "0000000000000"
    },
    "pollingInterval": 600,
    "appId": 435522656639081,
    "server": {
        "port": 3000
    }
}

Thhank you, Arno

**Comment by fredtux** [comment]
Have you logged out of messenger?

**Comment by sorenlouv** [comment]
Perhaps your `xs` value has expired. Try to update it by following this:
https://gist.github.com/sqren/0e4563f258c9e85e4ae1

**Comment by arno1234** [comment]
It was the XS value. 
Thank you, it's working again.

Arno
