### ISSUE TITLE
An error occured in buddyList [error : No users found]

### ISSUE THREAD

**Issue by tdelc** [sqren/fb-sleep-stats#64]
Hi,

When i use npm run scrape, i see this message in the command prompt. And the number of users in less than my actual number of contacts in fb.

I remember there was no problem at the beginning.

Do you know how to fix it ?

Thank for this strange tool.

Thomas

**Comment by sorenlouv** [comment]
There are different strategies for retrieving users. Sometimes it is not possible to retrieve the buddy list, and we fallback to an alternative strategy. 
What happens if you leave the process running? Doesn't it continue fetching users like: 

```
An error occurred in buddyList [error: No users found]
Thu Mar 03 2016 17:29:37 GMT+0100 (CET)  - Active users:  51 / 133
```

?

**Comment by tdelc** [comment]
Yes, it continue like you show.
It's strange, i have not the problem anymore...

**Comment by tdelc** [comment]
Its happend again : 
![image](https://cloud.githubusercontent.com/assets/13868149/13501976/235a8c64-e169-11e5-8928-d9ed4757f400.png)

**Comment by canvural** [comment]
Its not an important error. After failing its fetching users in a different way. So everything should be ok.

**Comment by tdelc** [comment]
Ah ok, thanks for the information.
