### ISSUE TITLE
Tell users to click the icons

### ISSUE THREAD

**Issue by kswahl1** [sqren/fb-sleep-stats#68]
It took me about two hours to figure out you are supposed to click the names in order for the charts to show up. Yes. I'm an idiot. May want to put a hover or something over there. Something to tell the user what to do. Or not. Whatever.

**Comment by Anubisss** [comment]
There is a hover.

**Comment by sorenlouv** [comment]
Thanks for the feedback. Hover was added recently. I hope this resolves the issues.
