### ISSUE TITLE
Unexpected error when scraping

### ISSUE THREAD

**Issue by RogerFederer17** [sqren/fb-sleep-stats#7]
Beginner here, when i run npm run scrape this error appears: 

> fb-sleep-stats@0.5.0 scrape C:\Users\omonoiadam\Desktop\fb-sleep
> node ./scrape.js
> C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:886
>     throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
>     ^
> Error: Cannot parse config file: 'C:\Users\omonoiadam\Desktop\fb-sleep\config\development.json': SyntaxError: Unexpected token '
>     at util.parseFile (C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:886:11)
>     at C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:685:28
>     at Array.forEach (native)
>     at C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:681:14
>     at Array.forEach (native)
>     at util.loadFileConfigs (C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:680:13)
>     at new Config (C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:119:27)
>     at Object.<anonymous> (C:\Users\omonoiadam\Desktop\fb-sleep\node_modules\config\lib\config.js:1688:31)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

What did i do wrong? Here's my config: 

```
{ 
'fbCookie': { 'c_user':"1000something61",
 "xs": "<redacted>
"}, "server": {
        "port": 3000
    }
}

```

**Comment by chhabs** [comment]
remove the "tab" after your cookie.

{ 
'fbCookie': { 'c_user':"1000something61",
 "xs": "<redacted>"}, "server": {
        "port": 3000
    }
}

**Comment by RogerFederer17** [comment]
Thank you, but i still get the error. Do i possibly need to rebuild it?(follow the instructions from the start?)

**Comment by dipples** [comment]
I had this error, and I started over. Make sure default.json is left alone while you edit development.json

also keep the last " on line 4 and "server": { on line 6

**Comment by sorenlouv** [comment]
As mentioned, make sure that both `default.json` and `development.json` follows this structure:

```
{
    "fbCookie": {
        "c_user": "",
        "xs": ""
    },
    "appId": 435522656639081,
    "server": {
        "port": 3000
    }
}
```

You can update it with values like so:

```
{
    "fbCookie": {
        "c_user": "YourFaceBookId",
        "xs": "YourXSValue"
    },
    "appId": 435522656639081,
    "server": {
        "port": 3000
    }
}
```

Be aware of trailing spaces/tabs, when you paste values into the config file.

**Comment by RogerFederer17** [comment]
Thank you guys, this problem is solved. Have a nice day

**Comment by petyusa** [comment]
Hi!

When running npm run scrape, I got this error message:

An error occured while scraping. Please check to make sure your development.json is correct [TypeError: Cannot read property '1' of null]

Here's how my development.json looks like:

```
{
    "fbCookie": {
        "c_user": "FB_ID",
        "xs": "XSValue"
    },
    "pollingInterval": 600,
    "appId": 435522656639081,
    "server": {
        "port": 3000
    }
}

```

Can you help me what's the problem?
