### ISSUE TITLE
Where are data saved?

### ISSUE THREAD

**Issue by ondrejsojka** [sqren/fb-sleep-stats#71]
I started to scrape yesterday about midday. Scraped to 8 PM, then I accidentally ran it from the wrong directory and it didn't scrape during the night. I want to delete all data and start scraping from scratch.

Where are online/offline data saved? In which format? (Just for me analysing them :smile:)

Thanks for reply.

**Comment by sorenlouv** [comment]
The data is stored in json format:
`src/server/services/db.json`
