### ISSUE TITLE
Installation impossible on ARM system ? (like rasp)

### ISSUE THREAD

**Issue by enzomerand** [sqren/fb-sleep-stats#75]
Hey,

I try to install fb-sleep-stats on raspbian ditrib. But i have this error : 
`ERROR in ./~/css-loader!./~/less-loader!./src/browser/components/main.less
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/etc/fb-sleep-stats/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/etc/fb-sleep-stats/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/etc/fb-sleep-stats/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/etc/fb-sleep-stats/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/browser/components/main.less 4:14-127
`

And just before, on the precedent command, i have : 
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
`

So, no possibilite on ARM ?

**Comment by canvural** [comment]
You need to update your node. What version are you using currently?

And you can ignore that warning about fsevents.

**Comment by enzomerand** [comment]
last version..

**Comment by sorenlouv** [comment]
What version is that?

**Comment by enzomerand** [comment]
node -v : v0.10.42
npm -v : 3.8.0

**Comment by sorenlouv** [comment]
You need to update your node version.

**Comment by sorenlouv** [comment]
You need at least 0.12.11. But 4.4.x and 5.7.x will also work.

**Comment by enzomerand** [comment]
I tested it and I will inform you if it works.
Thank you for this silly mistake :100:

**Comment by enzomerand** [comment]
it works ! thx
