### ISSUE TITLE
npm run webpack error

### ISSUE THREAD

**Issue by irfanshaik11** [sqren/fb-sleep-stats#82]
Hi, I've spent a long time troubleshooting this issue and I can't solve it.

I'm on windows
npm install -g gives me the following warnings 
![npminstall](https://cloud.githubusercontent.com/assets/14115825/13802004/d67bcda0-eb0d-11e5-9f91-4476726dda75.PNG)

and then npm run webpack gives me this error
![npmrunwebserver1](https://cloud.githubusercontent.com/assets/14115825/13802008/e458b3de-eb0d-11e5-9852-efb132ee51d4.PNG)

![npmrunwebserver2](https://cloud.githubusercontent.com/assets/14115825/13802019/fb9b10be-eb0d-11e5-9031-598f0856f0d3.PNG)

Thanks in advance.

**Comment by irfanshaik11** [comment]
sidenote: I tried to work this on an ubuntu system and it worked perfectly. Windows seems to have a lot of issues with this project

**Comment by sorenlouv** [comment]
Good to hear it works on Linux. It is developed on OSX, so Unix-like systems should be supported. Haven't tried it on Windows but it sounds like a couple of people were successful in running it.

You can try looking at https://github.com/sqren/fb-sleep-stats/issues/42 and https://github.com/sqren/fb-sleep-stats/issues/36
