### ISSUE TITLE
app is still in development: this app still is in development mode.........

### ISSUE THREAD

**Issue by arno1234** [sqren/fb-sleep-stats#86]
Hello,

Since a while I don't know exactly, the webserver is giving a error while logging in:

app is still in development: this app still is in development mode.........
![2016-03-24_09-05-46](https://cloud.githubusercontent.com/assets/17616320/14011521/a1ba220e-f19f-11e5-8df2-db24766c845a.jpg)

Any idea or sugestion?

Thank you, Arno

**Comment by Newtonishappy** [comment]
I have the same !

**Comment by erny83** [comment]
u have to change the app id and insert another 
https://gist.github.com/sqren/1ac0f5d316fcbd46d8c1
and after "npm run webpack"

**Comment by sorenlouv** [comment]
^^ What @erny83pd said. Unfortunately Facebook closed the default app, so you now have to setup your own.

**Comment by arno1234** [comment]
I did create my own app. Thank you. You better put in your maual that the  site url should be:: http://localhost:3000, otherwise it will not work. (The portnumber)

Thank you!

Arno

**Comment by sorenlouv** [comment]
@arno1234 Thanks for pointing that out. I've updated the gist
https://gist.github.com/sqren/1ac0f5d316fcbd46d8c1
