### ISSUE TITLE
How to interpret db.json?

### ISSUE THREAD

**Issue by irfanshaik11** [sqren/fb-sleep-stats#87]
I'm getting user ids followed by what I assume to be login times in my .json file

looks something like

100009558{
14013951
14012931}

how to convert 8 digit login numbers to real login times?

like 1401351 = March 23, 4:00 PM ?

**Comment by aaronhktan** [comment]
They should be 13 digit numbers; they are in the format of a [UNIX timestamp](https://en.wikipedia.org/wiki/Unix_time). The timestamp counts seconds since January 1 1970. You can use a tool like [this](http://www.epochconverter.com/) to convert it to a human-readable time.

**Comment by irfanshaik11** [comment]
thanks so much!
