### ISSUE TITLE
Problem with access from facebook

### ISSUE THREAD

**Issue by gntevetzakis** [sqren/fb-sleep-stats#88]
Everything on configurations seems good but I have problem with access from facebook

![fb_activity_error](https://cloud.githubusercontent.com/assets/18076491/14053687/b6bef728-f2db-11e5-8648-53978a572a88.jpg)

what is going wrong?

**Comment by sorenlouv** [comment]
This is a problem related to the settings in your Facebook app. 
https://www.facebook.com/help/community/question/?id=542958419109491

**Comment by gntevetzakis** [comment]
i have Insert site: http://localhost/ at the basic settings and I have enable "Embedded Browser OAuth Login" but still NOT working
