### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by clausbruun** [sqren/fb-sleep-stats#9]
![facebook_usage](https://cloud.githubusercontent.com/assets/105956/13219843/dcbeb09e-d972-11e5-96ed-27a0b00bba77.jpg)

Looks like bundle.js is missing? There is no "_bundle.js_" in "**public**"

![public_index_html__fb-sleep-stats__ _brackets](https://cloud.githubusercontent.com/assets/105956/13219884/14d60478-d973-11e5-9df6-d7f3ee485797.jpg)

**Comment by daveystruijk** [comment]
I got this too once. Might have simply forgotten to run build-minified. Anyway, the following (re-running the installation steps) helped for me:

```
rm -rf node_modules
npm install
npm run build-minified
```

**Comment by clausbruun** [comment]
That worked for me also, thanks @daveystruijk.

**Comment by sorenlouv** [comment]
Thanks for helping out @daveystruijk !
