### ISSUE TITLE
Problem npm run webpack (OS X)

### ISSUE THREAD

**Issue by BobyJackMitche** [sqren/fb-sleep-stats#90]
Hi, 

I tried the trouble shooting of running webpack but the issue still remains...

npm run webpack give me this error: 

![capture d ecran 2016-04-07 a 19 14 10](https://cloud.githubusercontent.com/assets/18333566/14360117/1a26d18c-fcf5-11e5-8930-0d837439dffd.png)

Sounds like my xs value is maybe not good looking but I double checked it..

**Comment by sorenlouv** [comment]
Your `development.json` contains invalid json. Try this tool to determine the issue:
http://jsonlint.com/

Paste the contents of development.json and it will highlight the errors.

**Comment by BobyJackMitche** [comment]
thanks for your quick answer! 
problem solved! 
Strange that Sublime Text did not highlight the mistake...
