### ISSUE TITLE
Is there any way to make the sidebar show all of my friends?

### ISSUE THREAD

**Issue by CastleCorp** [sqren/fb-sleep-stats#92]
I'm not sure how it is currently deciding which friends to show (my guess is recently active), but I would like to be able to see all of my friends.

Is this possible?

**Comment by sorenlouv** [comment]
It currently shows your most active friends, and limits to 20 to make the search faster. It will become horrendously slow if you show 400+.

You can manually change it here:
https://github.com/sqren/fb-sleep-stats/blob/master/src/browser/components/Users.jsx#L34

Remember to run `npm run webpack` afterwards

**Comment by CastleCorp** [comment]
I figured it out. 

I changed line 34 of Users.jsx from `users = users.slice(0, 20);` to `users = users.slice(0, users.length);`

**Comment by CastleCorp** [comment]
@sqren thanks! 

One other thing, which is more trivial. Is there a way I can have the search bar stay fixed in view when scrolling down the list?

**Comment by sorenlouv** [comment]
Probably less trivial actually :) 
Something with fixed positioning. Take a look here:
https://github.com/sqren/fb-sleep-stats/blob/master/src/browser/components/main.less#L8

Again: Remember to run `npm run webpack` afterwards

**Comment by sorenlouv** [comment]
If you are doing many changes, you can run webpack automatically on change by running:
`npm run webpack-watch`

**Comment by CastleCorp** [comment]
Ah perfect. That makes things much easier.

I am toying with the idea of doing a sleep study for my school. I will probably end up writing some scripts to make that easier. If anything comes from it, I'll share the result. 

Cheers

**Comment by sorenlouv** [comment]
Sounds cool. Good luck! :)
