### ISSUE TITLE
npm run webpack issue

### ISSUE THREAD

**Issue by calebwayseer** [sqren/fb-sleep-stats#94]
cant run the webpack, can somebody help me please?
linux mint 17.3
![screenshot-area-2016-05-10-103726](https://cloud.githubusercontent.com/assets/19290449/15154535/3d18b196-169b-11e6-9ddf-6ba9cd957599.png)

**Comment by sorenlouv** [comment]
You can try 

```
npm install -g webpack
npm run webpack
```

But you might have to upgrade your node version. What version are you running?

**Comment by calebwayseer** [comment]
Thanks for your quick answer!
nodejs version is v.4.4.4
Now I got this:
![screenshot-area-2016-05-10-112836](https://cloud.githubusercontent.com/assets/19290449/15156076/99eeaf0e-16a2-11e6-896e-04f6b8e97d11.png)
![screenshot-area-2016-05-10-112854](https://cloud.githubusercontent.com/assets/19290449/15156086/a2d843aa-16a2-11e6-935e-c3d9cc77e003.png)

**Comment by sorenlouv** [comment]
You should not run npm commands with sudo. To fix your permissions look here:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by calebwayseer** [comment]
Problem fixed!
You are a really good teacher!
Thanks!

**Comment by sorenlouv** [comment]
Glad to hear!
